In [3]:
import numpy as np

In [4]:
dizi = np.array([10,20,30])
print(dizi)

[10 20 30]


In [6]:
#Yukarıdaki kod bloğunda 1*3 lük bir matris oluşturuldu.Bunu shape fonksiyonunu kullanarak gösterelim.
print(dizi.shape)

(3,)


In [8]:
#Oluşturulan vektörü tekrar boyutlandrmak için reshape metodu kullanılır
#Şimdi oluşturulan dizi 3 satır 1 sütundan oluşan 3*1 lik matristir.
# !Dikkat! matris boyutlandırılırken reshape içine yazılan sayıların çarpımı dizinin eleman sayısına eşit olmalıdır
yeni_dizi = dizi.reshape(3,1)
print(yeni_dizi)

[[10]
 [20]
 [30]]


In [22]:
array = np.array([10,20,30,40,50,60,70,80,90])
# reshape yapmadan dizi boyutunu değiştirmek istersek [] içine yazılan değerler satırları ifade etmekte olup her satır virgül ile ayrılır
yeni_dizi_manuel = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Manuel olarak oluşturulan dizi : \n" , yeni_dizi_manuel)
new = array.reshape(3,3)
print("\nMatris Boyutu : " , new.ndim)
print("Matris veri tipi : " ,new.dtype.name)
print("Matris'in Eski Boyutu : " ,new.size)
print("Type: " , type(new))

Manuel olarak oluşturulan dizi : 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Matris Boyutu :  2
Matris veri tipi :  int32
Matris'in Eski Boyutu :  9
Type:  <class 'numpy.ndarray'>


In [40]:
# zeros ve ones metodları kullanılarak oluşturulam matrise 0 ve 1 değerleri atanabilir
zero= np.zeros((4,4))
print(zero)

print("\n")

ones = np.ones((4,4))
print(ones)

print("\n")

zero[3,2]=7
zero[1,3]=5
zero[2,3]=9
zero[2,2]=0
print(zero) 


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 5.]
 [0. 0. 0. 9.]
 [0. 0. 7. 0.]]


In [45]:
#boş matris oluşturuken değer atanması yapılmayan arraylere rastgele değer atanır
np.empty((3,7))
#sayıları üçer üçer 1'den 25'e kadar matris şeklinde yazdıralım
np.arange(1,25,3) 
#bu sefer üçer üçer değil de aralık verip kaç değer yazdırması gerektiğini gösterelim
#0 dan 10'a kadar 20 tane değeri yazdırıyoruz
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [48]:
# Numpy ile Temel İşlemler
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
# matriste toplama , çarpma.. işlemleri aynı satır ve sütunlar toplanarak yapılır 
print(a*b)

[5 7 9]
[ 4 10 18]


In [50]:
b=a 
c=a
b[0]=7
print(a,b,c)

[7 2 3] [7 2 3] [7 2 3]


In [62]:
matris = np.array([[45,78,55,60],[15,66,99,0],[14,78,99,10]])
copy = matris.copy()
print(matris[2,2])
print(matris[1,:])
print(matris[0,0:3])
print(matris[-1,:])
print(matris[:,-1])

99
[15 66 99  0]
[45 78 55]
[14 78 99 10]
[60  0 10]


In [66]:
# Çok boyutlu bir matrisi tek boyutlu hale getirmek için ravel metodu kullanılır
ravel = matris.ravel()
print(ravel)
#matriste traspose işlemi satır ve sütunların değişimi ile olur
transpose = matris.T
print(transpose)

[45 78 55 60 15 66 99  0 14 78 99 10]
[[45 15 14]
 [78 66 78]
 [55 99 99]
 [60  0 10]]
